# Generated by Django 2.0.5 on 2019-08-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=30)),
                ('cost', models.IntegerField(default=0)),
                ('operation_system', models.CharField(max_length=70)),
                ('ram', models.IntegerField(default=0)),
                ('core', models.IntegerField(default=0)),
                ('memory', models.IntegerField(default=0)),
                ('display_definition', models.CharField(max_length=20)),
                ('double_camera', models.BooleanField()),
                ('battery', models.IntegerField(default=0)),
            ],
        ),
    ]
